name: Packer validate pull-request
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2        
      - name: Validate Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.json
        env:
          PACKER_LOG: 1